package lokalize.transformers

import lokalize.models.LSArray
import lokalize.models.Options

class AndroidTransformer : AbstractTransformer() {

    override fun transformArray(array: LSArray): String {
        val builder = StringBuilder()
        builder.append("<string-array name=\"${array.key}\">").append('\n')
        array.lines.forEach {
            builder.append("<item>${it.value}</item>").append('\n')
        }
        builder.append("</string-array>")
        return builder.toString()
    }

    override fun transformComment(comment: String): String {
        return "<!-- $comment -->"
    }

    override fun transformKeyValue(key: String, value: String): String {
        val normalizedValue = this.normalize(value);

        var output = "<string name=\"$key\">$normalizedValue</string>"
        var currPos = 0
        var nbOcc = 1

        while (currPos != -1) {
            currPos = output.indexOf("%#$", currPos)

            output = this.setCharAt(output, currPos + 1, nbOcc.toChar())
            ++currPos
            ++nbOcc
        }

        return output
    }

    override fun insert(input: String?, newValues: String, options: Options): String {
        val inputString = input ?: ""

        val closeTagIndex = inputString.indexOf("</resources>")

        return if (closeTagIndex < 0) {
            "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n"
        } else {
            val autoGeneratedIndex = inputString.indexOf(AUTOGENERATED_TAG)
            if (autoGeneratedIndex >= 0) {
                inputString.substring(0, autoGeneratedIndex)
            } else {
                inputString.substring(0, closeTagIndex)
            }
        }
    }

    private fun normalize(value: String): String {
        var normalizedValue = value.replace("/%newline%/gi", "\\n")
        normalizedValue = normalizedValue.replace("/'/gi", "\\'")
        normalizedValue = normalizedValue.replace("/%([sdf])/gi", "%#$$$1")
        normalizedValue = normalizedValue.replace("/&/gi", "&amp;")
        normalizedValue = normalizedValue.replace("/\u00A0/gi", "\\u00A0");
        normalizedValue = normalizedValue.replace("/([^\\.]|^)(\\.{3})([^\\.]|$)/gi", "$1&#8230;$3")
        return normalizedValue
    }

    private fun setCharAt(str: String, index: Int, chr: Char): String {
        if (index > str.length - 1) return str
        return str.substring(0, index) + chr + str.substring(index + 1)
    }

    companion object {
        const val AUTOGENERATED_TAG = "<!-- AUTO-GENERATED -->"
    }
}